### ISSUE TITLE
Issue running setup-nuget on a windows runner

### ISSUE THREAD

**Issue by orenzi-tr** [NuGet/setup-nuget#25]
Hello
I'm trying to migrate my Jenkins pipeline that uses MSBuild and private repo to Github Actions running on windows runner. And I'm using the nuget/setup-NuGet plugin but I'm running in to errors.

For some reason the Variable NUGET is set with the value of: C:\actions-runner\_work\_tool\nuget.exe\5.8.1\x64/nuget.exe

And when MSBuild runs it also fails with this error:

![image](https://user-images.githubusercontent.com/72795921/110821852-26f30500-8299-11eb-9876-738654d1d701.png)

Any help would be greatly appreciated, 

Here is a sample of my Action code:

```
jobs:
  build-and-deploy:
    runs-on: 'self-hosted'

    steps:
    - uses: actions/checkout@master

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        # NuGet version to install. Can be `latest`, `preview`, a concrete version like `5.3.1`, or a semver range specifier like `5.x`.
        # nuget-version: # optional, default is latest
        # NuGet API Key to configure.
         nuget-api-key:  ${{ secrets.JFROG_ADMIN_KEY }}
        # Source to scope the NuGet API Key to.
         nuget-api-key-source: https://xxxxxxxxxxxxxxxxxxxx.jfrog.io/artifactory/api/nuget/nuget-central
    - run: gci env:* | sort-object name
    - run: nuget.exe sources list
    - name: Publish to folder
      run: msbuild buildApi.proj /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
```

**Comment by BertelBB** [comment]
Btw, @orenzi-tr I was able to resolve this by running the step that was failing in a `bash` shell.
I am however running in a `windows` cloud runner, not `self-hosted`.

```yaml
- name: Publish to folder
  shell: bash
  run: |
    # Replaces \ with /
    nugetPath="${NUGET//\\/\/}"
    
    NUGET=$nugetPath; msbuild ...
```

You will need to configure your VM to include `bash` in its `PATH` and perhaps something more.
See docs: <https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell>
