### ISSUE TITLE
NuGet doesn't work for private source

### ISSUE THREAD

**Issue by JacobWeyer** [NuGet/setup-nuget#48]
These same bits of code work fine on Azure DevOps but as I'm trying to port to Github Actions, I've tried this a variety of different ways at this point and end up in one of two places:

Method 1:
```
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-api-key-source: "https://pkgs.dev.azure.com/Company/Development/_packaging/AddInPackages/nuget/v3/index.json"
     
      - name: Restore Packages
        run: nuget restore Atlas.sln
```

Method 2:
```
nuget setApiKey *** -Source https://pkgs.dev.azure.com/NativLabs/Development/_packaging/AddInPackages/nuget/v3/index.json -NonInteractive
```

Both Result in the following
```
    [CredentialProvider]Using the ADAL UI  flow for uri https://pkgs.dev.azure.com/Company/Development/_packaging/AddInPackages/nuget/v3/index.json. User sign-in required in a pop-up authentication window.
```

Does a NonInteractive Flag needed to be added here? Am I missing something else?
